#include <day02/Utilities.ipp>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto input = util::Parse(util::GetInputFile("day02.txt"));

  std::vector<util::day02::Instruction> instructions;
  for(const auto& i : input)
  {
    instructions.push_back(util::day02::Instruction(i));
  }

  util::day02::Submarine_pt2 s;
  s.doInstructions(instructions);

  const auto result = s.x * s.y;
  std::cout << result << "\n";

  return EXIT_SUCCESS;
}
