#include <day01/Utilities.ipp>

#include <iostream>

// File auto-generated by StartNewDay

int main(int argc, char* argv[])
{
  const auto inputFile = util::GetInputFile("day01.txt");
  const auto contents = util::ContainerTo<int>(util::Parse(inputFile));

  auto increaseCount = 0;
  for(auto i = 1; i < contents.size(); ++i)
  {
    if(contents[i] - contents[i - 1] > 0)
    {
      ++increaseCount;
    }
  }

  std::cout << increaseCount << "\n";

  return EXIT_SUCCESS;
}
